image: Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  global:
    STRESS: 1
  matrix:
    - LUA: "lua 5.1"
    - LUA: "lua 5.2"
    - LUA: "lua 5.3"
    - LUA: "luajit 2.0"
    - LUA: "luajit 2.1"

before_build:
  - git submodule update --init --recursive
  - pip install hererocks
  - hererocks env --%LUA% -rlatest
  - call env\bin\activate

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --config %CONFIGURATION%

test_script:
  - lua ../tests/lua/run_tests